apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test1
  annotations:
    github.com/project-slug: dzemanov-org/test1
spec:
  type: other
  lifecycle: unknown
  owner: user:default/dzemanov
